title: Geekcamp.SG
email: info@geekcamp.sg
description: >
  Geekcamp.SG website
baseurl: ""
url: "http://www.geekcamp.sg"
# Build settings
markdown: kramdown

page_gen:
  - data: 'talks'
    template: 'talk'
    name: 'slug'
    dir: 'talks'
